version: 1
disable_existing_loggers: True
 
formatters:
  default:
    format: '{asctime} {name:<25.25} {funcName:<10.10} {levelname:<5.5}: {message}'
    datefmt: '%Y/%m/%d %H:%M:%S'
    style: '{'
 
handlers:
  console_handler:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default

  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    filename: 'logs/server.log'
    when: 'midnight'
    interval: 1
    backupCount: 7
    encoding: utf-8
    formatter: default
 
root:
  level: INFO
  handlers:
    - console_handler
    - file_handler

loggers:
  selenium.webdriver.remote.remote_connection:
    level: ERROR
    propagate: False
    handlers:
      - console_handler
      - file_handler
  urllib3.connectionpool:
    level: ERROR
    propagate: False
    handlers:
      - console_handler
      - file_handler
  sqlalchemy.engine:
    propagate: False
    level: ERROR
    handlers:
      - console_handler
      - file_handler
  alembic.runtime.migration:
    level: ERROR
    propagate: False
    handlers:
      - console_handler
      - file_handler
