"""Init.

Revision ID: bd33f9648aeb
Revises: 
Create Date: 2023-03-25 09:09:06.105459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd33f9648aeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend_result',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('modified', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backend_result')
    # ### end Alembic commands ###
